[2025-09-14T14:08:50.362+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-14T14:08:50.404+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_mlops_pl_full_load.create_insert_data manual__2025-09-14T14:08:30.473211+00:00 [queued]>
[2025-09-14T14:08:50.414+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_mlops_pl_full_load.create_insert_data manual__2025-09-14T14:08:30.473211+00:00 [queued]>
[2025-09-14T14:08:50.415+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2025-09-14T14:08:50.425+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): create_insert_data> on 2025-09-14 14:08:30.473211+00:00
[2025-09-14T14:08:50.433+0000] {standard_task_runner.py:72} INFO - Started process 20170 to run task
[2025-09-14T14:08:50.435+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_mlops_pl_full_load', 'create_insert_data', 'manual__2025-09-14T14:08:30.473211+00:00', '--job-id', '332', '--raw', '--subdir', 'DAGS_FOLDER/stock_pl_full_load.py', '--cfg-path', '/tmp/tmphmtx9h4t']
[2025-09-14T14:08:50.438+0000] {standard_task_runner.py:105} INFO - Job 332: Subtask create_insert_data
[2025-09-14T14:08:50.547+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_mlops_pl_full_load.create_insert_data manual__2025-09-14T14:08:30.473211+00:00 [running]> on host 7c4a8787553d
[2025-09-14T14:08:50.692+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khuong' AIRFLOW_CTX_DAG_ID='stock_mlops_pl_full_load' AIRFLOW_CTX_TASK_ID='create_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-14T14:08:30.473211+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-14T14:08:30.473211+00:00'
[2025-09-14T14:08:50.694+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-14T14:08:52.599+0000] {logging_mixin.py:190} INFO - Connect DuckDB Successfully!
[2025-09-14T14:09:15.884+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-09-14T14:09:15.885+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-09-14T14:09:15.890+0000] {process_utils.py:132} INFO - Sending 15 to group 20170. PIDs of all processes in the group: [20170]
[2025-09-14T14:09:15.891+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 20170
[2025-09-14T14:09:16.034+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-14T14:09:16.037+0000] {logging_mixin.py:190} INFO - Query interrupted
[2025-09-14T14:09:16.039+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-09-14T14:09:16.060+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-14T14:09:16.061+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_mlops_pl_full_load, task_id=create_insert_data, run_id=manual__2025-09-14T14:08:30.473211+00:00, execution_date=20250914T140830, start_date=20250914T140850, end_date=20250914T140916
[2025-09-14T14:09:16.104+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=20170, status='terminated', exitcode=0, started='14:08:49') (20170) terminated with exit code 0
